name: chess-gender-gap
channels:
  - conda-forge
dependencies:
  - python==3.9.15
  - pandas==1.5.2
  - tqdm==4.64.1
  - requests==2.28.1
  - seaborn==0.12.0
  - make==4.3
  # Pip
  - pip==22.3.1
  - pip:
